### PR TITLE
Added new parser for rspec tests.

### PR DESCRIPTION
**Pull request by calebmeyer**
I've never used pytest before, but these all pass, so I think I got it right.

Note that rspec doesn't distinguish between failures and errors, so I only implemented (and tested) num_failed

Let me know if there are more changes needed.

### CODE REVIEW

**Comment by calebmeyer** [comment]
It looks like the travis build failed due to a package (not this one) not getting installed on 2.7

**Comment by skoczen** [comment]
This is fantastic - thanks for submitting it.  I'm pretty slammed right now, but will get this reviewed, the coveralls thing fixed, and pushed out as soon as I get some spare cycles.

Would you mind updating your PR with your name and desired attribution in the AUTHORS file?

Thanks much for making polytester better!

-Steven

**Comment by calebmeyer** [comment]
I don't mind at all. Made the change. Let me know if there are any more changes needed.

**Comment by skoczen** [comment]
Merging this in, release shortly!

**Pull request merged**
